=== ymachkivskiy/hage/platform/config-xml/src/main/resources/age.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://age.iisg.agh.edu.pl/schema/age"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://age.iisg.agh.edu.pl/schema/age">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<!-- Top-level <configuration> element -->
	<xsd:element name="configuration">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:group ref="MultipleDefinition" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:group name="MultipleDefinition">
		<xsd:choice>
			<xsd:group ref="DefinitionElement"/>
			<xsd:group ref="CompositionElement"/>
		</xsd:choice>
	</xsd:group>

	<!-- Composition elements -->

	<xsd:group name="CompositionElement">
		<xsd:choice>
			<xsd:element ref="include" />
			<xsd:element ref="block"/>
		</xsd:choice>
	</xsd:group>

	<xsd:element name="include">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="block"/>
			</xsd:choice>
			<xsd:attribute name="file" type="NonEmptyString" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="block">
		<xsd:complexType>
			<xsd:group ref="MultipleDefinition" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:attribute name="name" type="NonEmptyString" use="required"/>
			<xsd:attribute name="override" type="xsd:boolean" use="optional" default="true" />
		</xsd:complexType>
	</xsd:element>

	<!-- Definition elements -->

	<xsd:group name="DefinitionElement">
		<xsd:choice>
			<xsd:group ref="ComponentElement" />
			<xsd:group ref="CollectionElement" />
		</xsd:choice>
	</xsd:group>

	<!-- Component elements -->
	<xsd:group name="ComponentElement">
		<xsd:choice>
			<xsd:element ref="agent" />
			<xsd:element ref="strategy" />
			<xsd:element ref="component" />
		</xsd:choice>
	</xsd:group>

	<xsd:complexType name="GeneralComponent">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="constructor-arg" />
			<xsd:element ref="property" />
			<xsd:group ref="MultipleDefinition" />
		</xsd:choice>
		<xsd:attribute name="name" type="NonEmptyString" />
		<xsd:attribute name="class" type="NonEmptyString" use="required" />
	</xsd:complexType>
	<xsd:element name="agent" type="GeneralComponent" />
	<xsd:element name="strategy" type="GeneralComponent" />
	<xsd:element name="component">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="GeneralComponent">
					<xsd:attribute name="isSingleton" type="xsd:boolean" default="true"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="ArgumentShortcutAble">
		<xsd:choice minOccurs="0">
			<xsd:group ref="DefinitionElement" />
			<xsd:group ref="ArgumentElement" />
		</xsd:choice>
		<xsd:attribute name="type" type="valueType" default="String"/>
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="ref" type="NonEmptyString" />
	</xsd:complexType>

	<xsd:element name="constructor-arg">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ArgumentShortcutAble">
					<xsd:attribute name="name" type="NonEmptyString" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="property">
	<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ArgumentShortcutAble">
					<xsd:attribute name="name" type="NonEmptyString" use="required" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<!-- Collection elements -->
	<xsd:group name="CollectionElement">
		<xsd:choice>
			<xsd:element ref="array" />
			<xsd:element ref="list" />
			<xsd:element ref="set" />
			<xsd:element ref="map" />
		</xsd:choice>
	</xsd:group>

	<xsd:complexType name="GeneralCollection" abstract="true">
		<xsd:attribute name="name" type="NonEmptyString" />
		<xsd:attribute name="isSingleton" type="xsd:boolean" default="false"/>
	</xsd:complexType>

	<xsd:complexType name="ListSetCollection">
		<xsd:complexContent>
			<xsd:extension base="GeneralCollection">
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:group ref="MultipleDefinition"/>
					<xsd:group ref="ArgumentElement"/>
					<xsd:element ref="multiple"/>
				</xsd:choice>
				<xsd:attribute name="value-type" type="NonEmptyString" default="java.lang.Object"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="multiple" >
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="DefinitionElement" />
				<xsd:group ref="ArgumentElement" />
			</xsd:choice>
			<xsd:attribute name="count" type="NonEmptyString" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="array" type="ListSetCollection" />
	<xsd:element name="list" type="ListSetCollection" />
	<xsd:element name="set" type="ListSetCollection" />

	<xsd:element name="map">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="GeneralCollection">
					<xsd:choice minOccurs="0" maxOccurs="unbounded">
						<xsd:group ref="MultipleDefinition"/>
						<xsd:element ref="entry" />
					</xsd:choice>
					<xsd:attribute name="value-type" type="NonEmptyString" default="java.lang.Object"/>
					<xsd:attribute name="key-type" type="NonEmptyString" default="java.lang.Object"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="entry">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="key" minOccurs="0"/>
				<xsd:choice minOccurs="0">
					<xsd:group ref="DefinitionElement" />
					<xsd:group ref="ArgumentElement" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="key" type="xsd:string"/>
			<xsd:attribute name="key-ref" type="NonEmptyString"/>
			<xsd:attribute name="value" type="xsd:string"/>
			<xsd:attribute name="value-ref" type="NonEmptyString"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="key">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="DefinitionElement" />
				<xsd:group ref="ArgumentElement" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<!-- Argument elements -->
	<xsd:group name="ArgumentElement">
		<xsd:choice>
			<xsd:element ref="reference" />
			<xsd:element ref="value" />
		</xsd:choice>
	</xsd:group>

	<xsd:element name="reference">
		<xsd:complexType>
			<xsd:attribute name="target" type="NonEmptyString" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType>
	    	<xsd:simpleContent>
	    		<xsd:extension base="xsd:string">
	         		<xsd:attribute name="type" type="valueType" use="optional" default="String"/>
	       		</xsd:extension>
	     	</xsd:simpleContent>
	 	</xsd:complexType>
	 </xsd:element>

	<!-- Simple internal types -->
	<xsd:simpleType name="NonEmptyString">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:pattern value=".*[^\s].*" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="valueType">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="String"></xsd:enumeration>
			<xsd:enumeration value="Integer"></xsd:enumeration>
			<xsd:enumeration value="Long"></xsd:enumeration>
			<xsd:enumeration value="Short"></xsd:enumeration>
			<xsd:enumeration value="Byte"></xsd:enumeration>
			<xsd:enumeration value="Boolean"></xsd:enumeration>
			<xsd:enumeration value="Float"></xsd:enumeration>
			<xsd:enumeration value="Double"></xsd:enumeration>
			<xsd:enumeration value="Class"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/properties/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <include file="classpath:examples/common.xml">
        <block name="workplaces">
            <component name="workplace" class="org.hage.platform.component.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent name="action" class="org.hage.platform.component.agent.SimpleAggregate">
                        <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="TheXFiles"/>
                        </component>

                        <property name="agents">
                            <list>
                                <agent name="scully" class="org.hage.examples.properties.PropertiesSimpleAgent">
                                    <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Scully"/>
                                    </component>
                                    <property name="actor" value="Gillian Anderson"/>
                                </agent>

                                <agent name="mulder" class="org.hage.examples.properties.PropertiesSimpleAgent">
                                    <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Mulder"/>
                                    </component>
                                    <property name="actor" value="David Duchovny"/>
                                </agent>

                                <agent name="skinner" class="org.hage.examples.properties.PropertiesSimpleAgent">
                                    <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Skinner"/>
                                    </component>
                                    <property name="actor" value="Mitch Pileggi"/>
                                </agent>
                            </list>
                        </property>
                    </agent>
                </property>
            </component>
        </block>
    </include>
</configuration>

=== ymachkivskiy/hage/archetypes/helloworld/src/main/resources/archetype-resources/applications/src/main/resources/helloworld.xml
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<include file="classpath:common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="action" class="org.jage.agent.SimpleAggregate">
						<component class="org.jage.address.agent.DefaultAgentAddressSupplier" >
							<constructor-arg name="nameTemplate" value="TheXFiles"/>
						</component>

						<property name="agents">
							<list>
								<agent name="scully" class="${package}.HelloWorldSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier" >
										<constructor-arg name="nameTemplate" value="Scully"/>
									</component>
								</agent>
								<agent name="mulder" class="${package}.HelloWorldSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier" >
										<constructor-arg name="nameTemplate" value="Mulder"/>
									</component>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/delegation/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="root" class="org.jage.examples.delegation.DelegationSimpleAggregate">
						<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
							<constructor-arg name="nameTemplate" value="Root"/>
						</component>
						<property name="echoStrategy" ref="parentStrategy"/>
						<property name="agents">
							<list>
								<agent name="level-1"
								       class="org.jage.examples.delegation.DelegationSimpleAggregate">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Level-1"/>
									</component>
									<property name="echoStrategy" ref="parentStrategy"/>
									<property name="childStrategy" value="parentStrategy"/>

									<property name="agents">
										<list>
											<agent name="level-1-1"
											       class="org.jage.examples.delegation.DelegationSimpleLeaf">
												<component
														class="org.jage.address.agent.DefaultAgentAddressSupplier">
													<constructor-arg name="nameTemplate" value="Level-1-1"/>
												</component>
											</agent>
											<agent name="level-1-2"
											       class="org.jage.examples.delegation.DelegationSimpleLeaf">
												<component
														class="org.jage.address.agent.DefaultAgentAddressSupplier">
													<constructor-arg name="nameTemplate" value="Level-1-2"/>
												</component>
											</agent>
										</list>
									</property>
								</agent>

								<agent name="level-2"
								       class="org.jage.examples.delegation.DelegationSimpleAggregate">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Level-2"/>
									</component>
									<property name="echoStrategy" ref="helloStrategy"/>
									<property name="childStrategy" value="helloStrategy"/>

									<property name="agents">
										<list>
											<agent name="level-2-1"
											       class="org.jage.examples.delegation.DelegationSimpleLeaf">
												<component
														class="org.jage.address.agent.DefaultAgentAddressSupplier">
													<constructor-arg name="nameTemplate" value="Level-2-1"/>
												</component>
											</agent>
										</list>
									</property>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>
		<block name="workplaceComponents" override="false">
			<strategy name="parentStrategy" class="org.jage.examples.delegation.EchoParentStrategy"/>
			<strategy name="helloStrategy" class="org.jage.examples.delegation.EchoHelloStrategy"/>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/configuration/age-array.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="action" class="org.jage.agent.SimpleAggregate">
						<property name="agents">
							<list>
								<agent name="scully" class="org.jage.examples.configuration.ArrayAgent">
									<array name="object-example"
									       value-type="org.jage.examples.configuration.ExampleClass">
										<component name="example-1" class="org.jage.examples.configuration.ExampleClass"
										           isSingleton="false">
											<constructor-arg value="First object"/>
										</component>
										<component name="example-2" class="org.jage.examples.configuration.ExampleClass"
										           isSingleton="false">
											<constructor-arg value="Second object"/>
										</component>
										<component name="example-3" class="org.jage.examples.configuration.ExampleClass"
										           isSingleton="false">
											<constructor-arg value="Third object"/>
										</component>
									</array>

									<array name="long-example" value-type="Long">
										<value type="Long">2</value>
										<value type="Long">4</value>
										<value type="Long">8</value>
									</array>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>

		<block name="stopCondition">
			<component name="stopCondition" class="org.jage.workplace.FixedStepCountStopCondition">
				<constructor-arg type="Long" value="1"/>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/messages/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="xfiles" class="org.jage.agent.SimpleAggregate">
						<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
							<constructor-arg name="nameTemplate" value="TheXFiles"/>
						</component>

						<property name="agents">
							<list>
								<agent name="scully" class="org.jage.examples.messages.MessagesSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Scully"/>
									</component>
									<property name="messageToSend" value="The Truth is Out There"/>
									<property name="receiver" value="Mulder"/>
								</agent>
								<agent name="mulder" class="org.jage.examples.messages.MessagesSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Mulder"/>
									</component>
									<property name="messageToSend" value="I want to believe"/>
									<property name="receiver" value="Scully"/>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/platform/config-xml/src/test/resources/full.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<component name="outerComponent" class="org.jage.platform.component.definition.ClassWithProperties" isSingleton="true">
		<constructor-arg><value>ABC</value></constructor-arg>
		<constructor-arg type="Integer" value="123"/>

		<property name="a"><value type="Integer">${a}</value></property>
		<property name="b" type="Float" value="${b}" />
		<property name="list"><reference target="list"/></property>
		<property name="map" ref="map" />
		<property name="set" ref="set" />
		<property name="objectArray" ref="objectArray" />
		<property name="longArray" ref="longArray" />

		<include file="classpath:valid.xml"/>

		<block name="collections">
			<list name="list" isSingleton="true">
				<reference target="innerComponent"/>
				<reference target="innerAgent"/>
				<multiple count="3">
					<component name="multipleComponent" class="java.lang.Object" />
				</multiple>
			</list>

			<map name="map" isSingleton="true">
				<entry key="2" value-ref="innerComponent" />
				<entry>
					<key><value>1</value></key>
					<reference target="innerAgent"/>
				</entry>
			</map>

			<set name="set" isSingleton="true">
				<reference target="innerComponent"/>
				<value type="Integer">2</value>
			</set>

			<array name="objectArray" isSingleton="true" value-type="Object">
				<reference target="innerComponent"/>
				<value type="Integer">2</value>
			</array>

			<array name="longArray" isSingleton="true" value-type="Long">
				<value type="Long">2</value>
				<value type="Long">4</value>
				<value type="Long">8</value>
			</array>
		</block>
	</component>

	<include file="classpath:included.xml">
		<block name="outer1">
			<list name="outer1List" />
		</block>

		<block name="outer2" override="false">
			<list name="outer2List" />
		</block>

		<block name="outer3">
			<list name="outer3List" />
		</block>

		<block name="outer4" override="false">
			<list name="outer4List" />
		</block>

		<block name="inner3">
			<list name="inner3List" />
		</block>

		<block name="inner4">
			<list name="inner4List" />
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/distributed/helloworld.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <component name="stopCondition" class="org.hage.platform.component.workplace.FixedStepCountStopCondition" isSingleton="true">
        <constructor-arg type="Long" value="20"/>
    </component>

    <component name="defaultAgentAddressSupplier" class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier"/>
    <component name="comparator" class="org.hage.platform.component.action.ordering.DefaultActionComparator" isSingleton="false"/>

    <agent name="workplace" class="org.hage.platform.component.workplace.SimpleWorkplace">
        <property name="agent" ref="aggregate"/>
        <agent name="aggregate" class="org.hage.platform.component.agent.SimpleAggregate">
            <property name="agents">
                <list name="agents">
                    <agent name="scully" class="org.hage.examples.helloworld.HelloWorldSimpleAgent">
                        <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="Scully"/>
                        </component>
                    </agent>
                    <agent name="mulder" class="org.hage.examples.helloworld.HelloWorldSimpleAgent">
                        <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="Mulder"/>
                        </component>
                    </agent>
                </list>
            </property>
        </agent>
    </agent>

    <component name="aggregateActionService" class="org.hage.platform.component.agent.AggregateActionService" isSingleton="false"/>
    <component name="aggregateQueryService" class="org.hage.platform.component.agent.AggregateQueryService" isSingleton="false"/>
    <component name="aggregateMessagingService" class="org.hage.platform.component.agent.AggregateMessagingService" isSingleton="false"/>

</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/monitoring/graphite/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <include file="classpath:examples/common.xml">
        <block name="workplaces">
            <component name="workplace" class="org.hage.platform.component.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent name="action" class="org.hage.platform.component.agent.SimpleAggregate">
                        <component class="org.hage.platform.util.communication.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="TheXFiles"/>
                        </component>
                        <property name="agents">
                            <list>
                                <agent name="scully" class="org.hage.examples.monitoring.MonitoringSimpleAgent">
                                    <component class="org.hage.platform.util.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Scully"/>
                                    </component>
                                </agent>
                                <agent name="mulder" class="org.hage.examples.monitoring.MonitoringSimpleAgent">
                                    <component class="org.hage.platform.util.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Mulder"/>
                                    </component>
                                </agent>
                            </list>
                        </property>
                    </agent>
                </property>
            </component>
        </block>
    </include>
</configuration>
