=== ymachkivskiy/hage/platform/config-xml/src/main/resources/age.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://age.iisg.agh.edu.pl/schema/age"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://age.iisg.agh.edu.pl/schema/age">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<!-- Top-level <configuration> element -->
	<xsd:element name="configuration">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:group ref="MultipleDefinition" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:group name="MultipleDefinition">
		<xsd:choice>
			<xsd:group ref="DefinitionElement"/>
			<xsd:group ref="CompositionElement"/>
		</xsd:choice>
	</xsd:group>

	<!-- Composition elements -->

	<xsd:group name="CompositionElement">
		<xsd:choice>
			<xsd:element ref="include" />
			<xsd:element ref="block"/>
		</xsd:choice>
	</xsd:group>

	<xsd:element name="include">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="block"/>
			</xsd:choice>
			<xsd:attribute name="file" type="NonEmptyString" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="block">
		<xsd:complexType>
			<xsd:group ref="MultipleDefinition" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:attribute name="name" type="NonEmptyString" use="required"/>
			<xsd:attribute name="override" type="xsd:boolean" use="optional" default="true" />
		</xsd:complexType>
	</xsd:element>

	<!-- Definition elements -->

	<xsd:group name="DefinitionElement">
		<xsd:choice>
			<xsd:group ref="ComponentElement" />
			<xsd:group ref="CollectionElement" />
		</xsd:choice>
	</xsd:group>

	<!-- Component elements -->
	<xsd:group name="ComponentElement">
		<xsd:choice>
			<xsd:element ref="agent" />
			<xsd:element ref="strategy" />
			<xsd:element ref="component" />
		</xsd:choice>
	</xsd:group>

	<xsd:complexType name="GeneralComponent">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="constructor-arg" />
			<xsd:element ref="property" />
			<xsd:group ref="MultipleDefinition" />
		</xsd:choice>
		<xsd:attribute name="name" type="NonEmptyString" />
		<xsd:attribute name="class" type="NonEmptyString" use="required" />
	</xsd:complexType>
	<xsd:element name="agent" type="GeneralComponent" />
	<xsd:element name="strategy" type="GeneralComponent" />
	<xsd:element name="component">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="GeneralComponent">
					<xsd:attribute name="isSingleton" type="xsd:boolean" default="true"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="ArgumentShortcutAble">
		<xsd:choice minOccurs="0">
			<xsd:group ref="DefinitionElement" />
			<xsd:group ref="ArgumentElement" />
		</xsd:choice>
		<xsd:attribute name="type" type="valueType" default="String"/>
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="ref" type="NonEmptyString" />
	</xsd:complexType>

	<xsd:element name="constructor-arg">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ArgumentShortcutAble">
					<xsd:attribute name="name" type="NonEmptyString" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="property">
	<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ArgumentShortcutAble">
					<xsd:attribute name="name" type="NonEmptyString" use="required" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<!-- Collection elements -->
	<xsd:group name="CollectionElement">
		<xsd:choice>
			<xsd:element ref="array" />
			<xsd:element ref="list" />
			<xsd:element ref="set" />
			<xsd:element ref="map" />
		</xsd:choice>
	</xsd:group>

	<xsd:complexType name="GeneralCollection" abstract="true">
		<xsd:attribute name="name" type="NonEmptyString" />
		<xsd:attribute name="isSingleton" type="xsd:boolean" default="false"/>
	</xsd:complexType>

	<xsd:complexType name="ListSetCollection">
		<xsd:complexContent>
			<xsd:extension base="GeneralCollection">
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:group ref="MultipleDefinition"/>
					<xsd:group ref="ArgumentElement"/>
					<xsd:element ref="multiple"/>
				</xsd:choice>
				<xsd:attribute name="value-type" type="NonEmptyString" default="java.lang.Object"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="multiple" >
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="DefinitionElement" />
				<xsd:group ref="ArgumentElement" />
			</xsd:choice>
			<xsd:attribute name="count" type="NonEmptyString" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="array" type="ListSetCollection" />
	<xsd:element name="list" type="ListSetCollection" />
	<xsd:element name="set" type="ListSetCollection" />

	<xsd:element name="map">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="GeneralCollection">
					<xsd:choice minOccurs="0" maxOccurs="unbounded">
						<xsd:group ref="MultipleDefinition"/>
						<xsd:element ref="entry" />
					</xsd:choice>
					<xsd:attribute name="value-type" type="NonEmptyString" default="java.lang.Object"/>
					<xsd:attribute name="key-type" type="NonEmptyString" default="java.lang.Object"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="entry">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="key" minOccurs="0"/>
				<xsd:choice minOccurs="0">
					<xsd:group ref="DefinitionElement" />
					<xsd:group ref="ArgumentElement" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="key" type="xsd:string"/>
			<xsd:attribute name="key-ref" type="NonEmptyString"/>
			<xsd:attribute name="value" type="xsd:string"/>
			<xsd:attribute name="value-ref" type="NonEmptyString"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="key">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="DefinitionElement" />
				<xsd:group ref="ArgumentElement" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<!-- Argument elements -->
	<xsd:group name="ArgumentElement">
		<xsd:choice>
			<xsd:element ref="reference" />
			<xsd:element ref="value" />
		</xsd:choice>
	</xsd:group>

	<xsd:element name="reference">
		<xsd:complexType>
			<xsd:attribute name="target" type="NonEmptyString" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType>
	    	<xsd:simpleContent>
	    		<xsd:extension base="xsd:string">
	         		<xsd:attribute name="type" type="valueType" use="optional" default="String"/>
	       		</xsd:extension>
	     	</xsd:simpleContent>
	 	</xsd:complexType>
	 </xsd:element>

	<!-- Simple internal types -->
	<xsd:simpleType name="NonEmptyString">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:pattern value=".*[^\s].*" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="valueType">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="String"></xsd:enumeration>
			<xsd:enumeration value="Integer"></xsd:enumeration>
			<xsd:enumeration value="Long"></xsd:enumeration>
			<xsd:enumeration value="Short"></xsd:enumeration>
			<xsd:enumeration value="Byte"></xsd:enumeration>
			<xsd:enumeration value="Boolean"></xsd:enumeration>
			<xsd:enumeration value="Float"></xsd:enumeration>
			<xsd:enumeration value="Double"></xsd:enumeration>
			<xsd:enumeration value="Class"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/multiworkplace/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <include file="classpath:examples/common.xml">
        <block name="workplaces">
            <!-- Workplace 1 -->
            <component name="workplace1" class="org.hage.platform.component.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent name="action" class="org.hage.platform.component.agent.SimpleAggregate">
                        <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="TheXFiles"/>
                        </component>
                        <property name="agents">
                            <list>
                                <agent name="scully" class="org.hage.examples.multiworkplace.MultiworkplaceSimpleAgent">
                                    <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Scully"/>
                                    </component>
                                </agent>
                                <agent name="mulder" class="org.hage.examples.multiworkplace.MultiworkplaceSimpleAgent">
                                    <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="Mulder"/>
                                    </component>
                                </agent>
                            </list>
                        </property>
                    </agent>
                </property>
                <!--<property name="queries">
                    <list>
                        <component class="org.hage.examples.multiworkplace.MultiworkplacePropertiesQuery"
                                   isSingleton="false"/>
                    </list>
                </property>-->
            </component>

            <!-- Workplace 2 -->
            <component name="workplace2" class="org.hage.platform.component.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent class="org.hage.platform.component.agent.SimpleAggregate">
                        <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="GoldenEye"/>
                        </component>
                        <property name="agents">
                            <list>
                                <agent name="bond" class="org.hage.examples.multiworkplace.MultiworkplaceSimpleAgent">
                                    <component class="org.hage.platform.communication.address.agent.DefaultAgentAddressSupplier">
                                        <constructor-arg name="nameTemplate" value="JamesBond"/>
                                    </component>
                                </agent>
                            </list>
                        </property>
                    </agent>
                </property>
                <!--<property name="queries">
                    <list>
                        <component class="org.hage.examples.multiworkplace.MultiworkplacePropertiesQuery"
                                   isSingleton="false"/>
                    </list>
                </property>-->
            </component>
        </block>
    </include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/helloworld/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="xfiles" class="org.jage.agent.SimpleAggregate">
						<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
							<constructor-arg name="nameTemplate" value="TheXFiles"/>
						</component>
						<property name="agents">
							<list>
								<agent name="scully" class="org.jage.examples.helloworld.HelloWorldSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Scully"/>
									</component>
								</agent>
								<agent name="mulder" class="org.jage.examples.helloworld.HelloWorldSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Mulder"/>
									</component>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/properties/xml/age2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<!-- This example runs Agents which has a property of type ExampleComponent
		which contract is read from XML file ExampleComponent.contract.xml. ExampleComponent
		prints it's properties using printComponentInfo method. -->

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="action" class="org.jage.agent.SimpleAggregate">
						<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
							<constructor-arg name="nameTemplate" value="TheXFiles"/>
						</component>

						<property name="agents">
							<list>
								<agent name="scully"
								       class="org.jage.examples.properties.xml.XMLContractHelloWorldSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Scully"/>
									</component>
									<property name="exampleComponent">
										<agent name="exampleComponentForScully"
										       class="org.jage.examples.properties.xml.ExampleComponent">
											<property name="name" value="Scully's component"/>
											<property name="version" value="1" type="Integer"/>
											<property name="holder">
												<component name="sampleObject" class="java.lang.Object"/>
											</property>
										</agent>
									</property>
								</agent>
								<agent name="mulder"
								       class="org.jage.examples.properties.xml.XMLContractHelloWorldSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Mulder"/>
									</component>
									<property name="exampleComponent">
										<agent name="exampleComponentForMulder"
										       class="org.jage.examples.properties.xml.ExampleComponent">
											<property name="name" value="Mulder's component"/>
											<property name="version" value="777" type="Integer"/>
											<property name="holder">
												<component name="sampleObject" class="java.lang.Object"/>
											</property>
										</agent>
									</property>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/algorithms/applications/vanilla-genetic/src/main/resources/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <include file="classpath:common.xml">
        <block name="workplaces">
            <component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent name="action" class="org.jage.agent.SimpleAggregate">
                        <property name="agents">
                            <list>
                                <agent name="agent" class="org.jage.genetic.agent.GeneticActionDrivenAgent"/>
                            </list>
                        </property>

                        <!-- Action Strategies -->
                        <strategy name="geneticActionPreparator"
                                  class="org.jage.genetic.action.GeneticActionPreparer"/>
                        <strategy name="geneticActionComparator"
                                  class="org.jage.genetic.action.GeneticActionComparator"/>

                        <strategy name="initializationAction"
                                  class="org.jage.genetic.action.InitializationActionStrategy"/>
                        <strategy name="preselectionAction" class="org.jage.genetic.action.PreselectionActionStrategy"/>
                        <strategy name="variationAction" class="org.jage.genetic.action.VariationActionStrategy"/>
                        <strategy name="evaluationAction" class="org.jage.genetic.action.EvaluationActionStrategy"/>
                        <strategy name="statisticsUpdateAction"
                                  class="org.jage.genetic.action.StatisticsUpdateActionStrategy"/>
                    </agent>
                </property>
            </component>
        </block>

        <block name="propertygatherer">
            <component class="org.jage.monitoring.gatherer.DefaultComputationInstanceProvider"/>
            <component class="org.jage.monitoring.typesafe.TypeSafeConfigMonitoring">
                <property name="config" value="monitoring"/>
            </component>
        </block>

        <block name="workplaceComponents" override="false">
            <!-- General Strategies -->
            <strategy name="populationFactory" class="org.jage.population.PopulationFactory">
                <property name="populationSize" type="Integer" value="${population.size}"/>
            </strategy>
            <strategy name="solutionFactory" class="org.jage.solution.realvalued.RealValuedSolutionFactory"/>

            <strategy name="populationEvaluator" class="org.jage.evaluation.SequentialPopulationEvaluator"/>
            <strategy name="solutionEvaluator" class="org.jage.evaluation.realvalued.RastriginEvaluator"/>
            <strategy name="problem" class="org.jage.problem.realvalued.RastriginProblem">
                <constructor-arg type="Integer" value="${problem.size}"/>
            </strategy>

            <strategy name="rand" class="org.jage.random.SimpleGenerator">
                <constructor-arg type="Long" value="1234567890"/>
            </strategy>

            <!-- Genetic Strategies -->

            <strategy name="rankPreselection" class="org.jage.genetic.preselection.RankPreselection">
                <strategy name="preselection" class="org.jage.genetic.preselection.StochasticPreselection">
                    <strategy name="scaling" class="org.jage.genetic.scaling.SimpleScaling"/>
                </strategy>
            </strategy>

            <strategy name="geneticOperators" class="org.jage.variation.VariationOperator">
                <strategy name="recombinePopulation" class="org.jage.variation.recombination.PairedRecombinePopulation">
                    <property name="chanceToRecombine" type="Double" value="${individual.chanceToRecombine}"/>
                    <strategy name="recombineSolutions"
                              class="org.jage.variation.recombination.realvalued.AverageRecombine"/>
                </strategy>
                <strategy name="mutatePopulation" class="org.jage.variation.mutation.IndividuallyMutatePopulation">
                    <property name="chanceToMutate" type="Double" value="${individual.chanceToMutate}"/>
                    <strategy name="mutateSolution"
                              class="org.jage.variation.mutation.realvalued.NormalMicroMacroMutate">
                        <property name="chanceToMutate" type="Double" value="${feature.chanceToMutate}"/>
                        <property name="mutationRange" type="Double" value="${feature.mutationRange}"/>
                    </strategy>
                </strategy>
            </strategy>
        </block>
    </include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/monitoring/node.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <component class="org.jage.communication.HazelcastCommunicationManager"/>
    <component class="org.jage.configuration.service.ConfigurationHubService"/>
    <component class="org.jage.configuration.service.ConfigurationLoaderService"/>
    <component class="org.jage.bus.EventBus">
        <constructor-arg name="name" type="String" value="mainBus"/>
    </component>

    <component name="workplaceManager" class="org.jage.workplace.manager.DefaultWorkplaceManager"/>
    <component class="org.jage.lifecycle.AutoExitHook"/>

    <block name="monitoring">
        <component class="org.jage.monitoring.Monitoring">
            <component class="org.jage.monitoring.config.DefaultComputationInstanceProvider"/>
            <component class="org.jage.monitoring.config.ExecutorProvider"/>
            <component class="org.jage.monitoring.config.ExecutorShutdownCaller"/>
            <component class="org.jage.monitoring.config.RxComputationSchedulerProvider"/>

            <component name="stringQuery" class="org.jage.monitoring.supplier.AgentStringQuerySupplier">
                <constructor-arg name="query" value="/TheXFiles/Scully@alienAbductions"/>
            </component>

            <component name="random" class="org.jage.monitoring.supplier.RandomSupplier"/>

            <component name="randomProvider" class="org.jage.monitoring.observable.ObservableProvider">
                <constructor-arg name="supplier" ref="random"/>
                <constructor-arg name="rate" value="1000" type="Long"/>
            </component>

            <component name="queryProvider" class="org.jage.monitoring.observable.ObservableProvider">
                <constructor-arg name="supplier" ref="stringQuery"/>
                <constructor-arg name="rate" value="1000" type="Long"/>
            </component>

            <list name="observers">
                <component name="logging" class="org.jage.monitoring.observer.LoggingObserver"/>
            </list>
            <constructor-arg>
                <component class="org.jage.monitoring.config.XmlConfig">
                    <constructor-arg>
                        <list>
                            <component name="handler1" class="org.jage.monitoring.handler.HandlerFactoryProvider">
                                <constructor-arg name="name" value="handler1"/>
                                <constructor-arg name="observableProviders">
                                    <list name="observableProviders">
                                        <reference target="queryProvider"/>
                                        <reference target="randomProvider"/>
                                    </list>
                                </constructor-arg>
                                <constructor-arg name="observers" ref="observers"/>
                                <constructor-arg name="clazz" value="org.jage.monitoring.handler.AvgHandlerFactory"/>
                                <constructor-arg name="method" value="create"/>
                            </component>

                            <component name="handler2" class="org.jage.monitoring.handler.HandlerFactoryProvider">
                                <constructor-arg name="name" value="handler2"/>
                                <constructor-arg name="observableProviders">
                                    <list>
                                        <reference target="queryProvider"/>
                                    </list>
                                </constructor-arg>
                                <constructor-arg name="observers" ref="observers"/>
                                <constructor-arg name="clazz" value="org.jage.monitoring.handler.BasicHandlerFactory"/>
                                <constructor-arg name="method" value="create"/>
                            </component>
                        </list>
                    </constructor-arg>
                </component>
            </constructor-arg>

            <constructor-arg>
                <component class="org.jage.monitoring.config.TypeSafeConfig">
                    <constructor-arg value="examples/monitoring/monitoring"/>
                </component>
            </constructor-arg>
        </component>
    </block>
</configuration>
