=== ymachkivskiy/hage/platform/config-xml/src/main/resources/age.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://age.iisg.agh.edu.pl/schema/age"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://age.iisg.agh.edu.pl/schema/age">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<!-- Top-level <configuration> element -->
	<xsd:element name="configuration">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:group ref="MultipleDefinition" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<xsd:group name="MultipleDefinition">
		<xsd:choice>
			<xsd:group ref="DefinitionElement"/>
			<xsd:group ref="CompositionElement"/>
		</xsd:choice>
	</xsd:group>

	<!-- Composition elements -->

	<xsd:group name="CompositionElement">
		<xsd:choice>
			<xsd:element ref="include" />
			<xsd:element ref="block"/>
		</xsd:choice>
	</xsd:group>

	<xsd:element name="include">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="block"/>
			</xsd:choice>
			<xsd:attribute name="file" type="NonEmptyString" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="block">
		<xsd:complexType>
			<xsd:group ref="MultipleDefinition" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:attribute name="name" type="NonEmptyString" use="required"/>
			<xsd:attribute name="override" type="xsd:boolean" use="optional" default="true" />
		</xsd:complexType>
	</xsd:element>

	<!-- Definition elements -->

	<xsd:group name="DefinitionElement">
		<xsd:choice>
			<xsd:group ref="ComponentElement" />
			<xsd:group ref="CollectionElement" />
		</xsd:choice>
	</xsd:group>

	<!-- Component elements -->
	<xsd:group name="ComponentElement">
		<xsd:choice>
			<xsd:element ref="agent" />
			<xsd:element ref="strategy" />
			<xsd:element ref="component" />
		</xsd:choice>
	</xsd:group>

	<xsd:complexType name="GeneralComponent">
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element ref="constructor-arg" />
			<xsd:element ref="property" />
			<xsd:group ref="MultipleDefinition" />
		</xsd:choice>
		<xsd:attribute name="name" type="NonEmptyString" />
		<xsd:attribute name="class" type="NonEmptyString" use="required" />
	</xsd:complexType>
	<xsd:element name="agent" type="GeneralComponent" />
	<xsd:element name="strategy" type="GeneralComponent" />
	<xsd:element name="component">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="GeneralComponent">
					<xsd:attribute name="isSingleton" type="xsd:boolean" default="true"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="ArgumentShortcutAble">
		<xsd:choice minOccurs="0">
			<xsd:group ref="DefinitionElement" />
			<xsd:group ref="ArgumentElement" />
		</xsd:choice>
		<xsd:attribute name="type" type="valueType" default="String"/>
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="ref" type="NonEmptyString" />
	</xsd:complexType>

	<xsd:element name="constructor-arg">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ArgumentShortcutAble">
					<xsd:attribute name="name" type="NonEmptyString" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="property">
	<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ArgumentShortcutAble">
					<xsd:attribute name="name" type="NonEmptyString" use="required" />
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<!-- Collection elements -->
	<xsd:group name="CollectionElement">
		<xsd:choice>
			<xsd:element ref="array" />
			<xsd:element ref="list" />
			<xsd:element ref="set" />
			<xsd:element ref="map" />
		</xsd:choice>
	</xsd:group>

	<xsd:complexType name="GeneralCollection" abstract="true">
		<xsd:attribute name="name" type="NonEmptyString" />
		<xsd:attribute name="isSingleton" type="xsd:boolean" default="false"/>
	</xsd:complexType>

	<xsd:complexType name="ListSetCollection">
		<xsd:complexContent>
			<xsd:extension base="GeneralCollection">
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:group ref="MultipleDefinition"/>
					<xsd:group ref="ArgumentElement"/>
					<xsd:element ref="multiple"/>
				</xsd:choice>
				<xsd:attribute name="value-type" type="NonEmptyString" default="java.lang.Object"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="multiple" >
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="DefinitionElement" />
				<xsd:group ref="ArgumentElement" />
			</xsd:choice>
			<xsd:attribute name="count" type="NonEmptyString" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="array" type="ListSetCollection" />
	<xsd:element name="list" type="ListSetCollection" />
	<xsd:element name="set" type="ListSetCollection" />

	<xsd:element name="map">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="GeneralCollection">
					<xsd:choice minOccurs="0" maxOccurs="unbounded">
						<xsd:group ref="MultipleDefinition"/>
						<xsd:element ref="entry" />
					</xsd:choice>
					<xsd:attribute name="value-type" type="NonEmptyString" default="java.lang.Object"/>
					<xsd:attribute name="key-type" type="NonEmptyString" default="java.lang.Object"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="entry">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="key" minOccurs="0"/>
				<xsd:choice minOccurs="0">
					<xsd:group ref="DefinitionElement" />
					<xsd:group ref="ArgumentElement" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="key" type="xsd:string"/>
			<xsd:attribute name="key-ref" type="NonEmptyString"/>
			<xsd:attribute name="value" type="xsd:string"/>
			<xsd:attribute name="value-ref" type="NonEmptyString"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="key">
		<xsd:complexType>
			<xsd:choice>
				<xsd:group ref="DefinitionElement" />
				<xsd:group ref="ArgumentElement" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>

	<!-- Argument elements -->
	<xsd:group name="ArgumentElement">
		<xsd:choice>
			<xsd:element ref="reference" />
			<xsd:element ref="value" />
		</xsd:choice>
	</xsd:group>

	<xsd:element name="reference">
		<xsd:complexType>
			<xsd:attribute name="target" type="NonEmptyString" use="required" />
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="value">
		<xsd:complexType>
	    	<xsd:simpleContent>
	    		<xsd:extension base="xsd:string">
	         		<xsd:attribute name="type" type="valueType" use="optional" default="String"/>
	       		</xsd:extension>
	     	</xsd:simpleContent>
	 	</xsd:complexType>
	 </xsd:element>

	<!-- Simple internal types -->
	<xsd:simpleType name="NonEmptyString">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1" />
			<xsd:pattern value=".*[^\s].*" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="valueType">
		<xsd:annotation>
			<xsd:documentation></xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="String"></xsd:enumeration>
			<xsd:enumeration value="Integer"></xsd:enumeration>
			<xsd:enumeration value="Long"></xsd:enumeration>
			<xsd:enumeration value="Short"></xsd:enumeration>
			<xsd:enumeration value="Byte"></xsd:enumeration>
			<xsd:enumeration value="Boolean"></xsd:enumeration>
			<xsd:enumeration value="Float"></xsd:enumeration>
			<xsd:enumeration value="Double"></xsd:enumeration>
			<xsd:enumeration value="Class"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/migration/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <include file="classpath:examples/common.xml">
        <block name="workplaces">
            <component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent name="rootSimpleAggregate" class="org.jage.agent.SimpleAggregate">
                        <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                            <constructor-arg name="nameTemplate" value="TheXFiles"/>
                        </component>
                        <list name="simpleAgents">
                            <agent name="squeeze" class="org.jage.agent.SimpleAggregate">
                                <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                    <constructor-arg name="nameTemplate" value="Squeeze"/>
                                </component>
                                <property name="agents">
                                    <list name="agents">
                                        <agent name="scully" class="org.jage.examples.migration.CrawlingSimpleAgent">
                                            <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                                <constructor-arg name="nameTemplate" value="Scully"/>
                                            </component>
                                        </agent>
                                        <agent name="mulder" class="org.jage.examples.migration.CrawlingSimpleAgent">
                                            <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                                <constructor-arg name="nameTemplate" value="Mulder"/>
                                            </component>
                                        </agent>
                                    </list>
                                </property>
                            </agent>

                            <agent name="shadows" class="org.jage.agent.SimpleAggregate">
                                <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                    <constructor-arg name="nameTemplate" value="Shadows"/>
                                </component>

                                <property name="agents">
                                    <list name="agents">
                                        <agent name="skinner" class="org.jage.examples.migration.CrawlingSimpleAgent">
                                            <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                                <constructor-arg name="nameTemplate" value="Skinner"/>
                                            </component>
                                        </agent>
                                    </list>
                                </property>
                            </agent>

                            <agent name="space" class="org.jage.agent.SimpleAggregate">
                                <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                    <constructor-arg name="nameTemplate" value="Space"/>
                                </component>

                                <property name="agents">
                                    <list name="agents">
                                        <agent name="doggett" class="org.jage.examples.migration.CrawlingSimpleAgent">
                                            <component class="org.jage.address.agent.DefaultAgentAddressSupplier">
                                                <constructor-arg name="nameTemplate" value="Doggett"/>
                                            </component>
                                        </agent>
                                    </list>
                                </property>
                            </agent>
                        </list>
                        <property name="agents" ref="simpleAgents"/>
                    </agent>
                </property>
            </component>
        </block>
    </include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/properties/xml/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<!-- System which contains 3 PropertiesSimpleAgents which: - uses strategy
		functionCounter to compute square sum of two numbers (x & y) - randomly watch
		neighbors and writes them properties to console SimpleFunctionCounter contract
		is read from XML file SimpleFunctionCounter.contract.xml. -->

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="action" class="org.jage.agent.SimpleAggregate">
						<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
							<constructor-arg name="nameTemplate" value="TheXFiles"/>
						</component>

						<strategy name="functionCounter1"
						          class="org.jage.examples.properties.xml.SimpleFunctionCounter">
							<property name="x" type="Integer" value="1"/>
							<property name="y" type="Integer" value="2"/>
						</strategy>
						<strategy name="functionCounter2"
						          class="org.jage.examples.properties.xml.SimpleFunctionCounter">
							<property name="x" type="Integer" value="10"/>
							<property name="y" type="Integer" value="20"/>
						</strategy>
						<strategy name="functionCounter3"
						          class="org.jage.examples.properties.xml.SimpleFunctionCounter">
							<property name="x" type="Integer" value="100"/>
							<property name="y" type="Integer" value="200"/>
						</strategy>

						<property name="agents">
							<list>
								<agent name="scully" class="org.jage.examples.properties.xml.PropertiesSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Scully"/>
									</component>
									<property name="actor" value="Gillian Anderson"/>
									<property name="functionCounter" ref="functionCounter1"/>
								</agent>
								<agent name="mulder" class="org.jage.examples.properties.xml.PropertiesSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Mulder"/>
									</component>
									<property name="actor" value="David Duchovny"/>
									<property name="functionCounter" ref="functionCounter2"/>
								</agent>
								<agent name="skinner" class="org.jage.examples.properties.xml.PropertiesSimpleAgent">
									<component class="org.jage.address.agent.DefaultAgentAddressSupplier">
										<constructor-arg name="nameTemplate" value="Skinner"/>
									</component>
									<property name="actor" value="Mitch Pileggi"/>
									<property name="functionCounter" ref="functionCounter3"/>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/monitoring/graphite/node.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <component class="org.hage.communication.HazelcastCommunicationManager"/>
    <component class="org.hage.configuration.service.ConfigurationStorageService"/>
    <component class="org.hage.configuration.service.ConfigurationLoaderService"/>
    <component class="org.hage.bus.EventBus">
        <constructor-arg name="name" type="String" value="mainBus"/>
    </component>

    <component name="workplaceManager" class="org.hage.platform.component.workplace.manager.DefaultWorkplaceManager"/>

    <block name="monitoring">
        <component class="org.hage.monitoring.gatherer.DefaultComputationInstanceProvider"/>

        <component name="handler1" class="org.hage.monitoring.handler.HandlerFactoryProvider">
            <constructor-arg name="name" value="first.alienAbductions"/>
            <constructor-arg name="observableProviders" ref="observableProviders"/>
            <constructor-arg name="observers" ref="selectFirstList"/>
            <constructor-arg name="clazz" value="org.hage.monitoring.handler.BasicHandlerFactory"/>
            <constructor-arg name="method" value="create"/>
        </component>

        <component name="handler1" class="org.hage.monitoring.handler.HandlerFactoryProvider">
            <constructor-arg name="name" value="second.alienAbductions"/>
            <constructor-arg name="observableProviders" ref="observableProviders"/>
            <constructor-arg name="observers" ref="selectSecondList"/>
            <constructor-arg name="clazz" value="org.hage.monitoring.handler.BasicHandlerFactory"/>
            <constructor-arg name="method" value="create"/>
        </component>

        <!-- Supplier -->
        <component name="query" class="org.hage.monitoring.supplier.AgentQuerySupplier">
            <constructor-arg>
                <component class="org.hage.examples.monitoring.ExampleQuery"/>
            </constructor-arg>
        </component>

        <!-- Observables -->
        <list name="observableProviders">
            <component name="queryProvider" class="org.hage.monitoring.observable.ObservableProvider">
                <constructor-arg name="supplier" ref="stringQuery"/>
                <constructor-arg name="rate" value="500" type="Long"/>
            </component>
        </list>

        <!--  BOOM -->
        <!-- Consumers -->
        <component name="selectFirst" class="org.hage.examples.monitoring.SelectNthElement">
            <constructor-arg name="target" ref="graphiteConsumer"/>
            <constructor-arg name="index" value="1" type="Integer"/>
        </component>
        <component name="selectSecond" class="org.hage.examples.monitoring.SelectNthElement">
            <constructor-arg name="target" ref="graphiteConsumer"/>
            <constructor-arg name="index" value="1" type="Integer"/>
        </component>
        <component name="graphiteConsumer" class="org.hage.monitoring.graphite.GraphiteConsumer"></component>
    </block>

</configuration>

=== ymachkivskiy/hage/algorithms/applications/emas-app/src/main/resources/node.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <component class="org.jage.communication.HazelcastCommunicationManager"/>
    <component class="org.jage.configuration.service.ConfigurationStorageService"/>
    <component class="org.jage.configuration.service.ConfigurationLoaderService"/>
    <component class="org.jage.bus.EventBus">
        <constructor-arg name="name" type="String" value="mainBus"/>
    </component>

    <component name="workplaceManager"
               class="org.jage.workplace.manager.DefaultWorkplaceManager"/>

    <component class="org.jage.lifecycle.AutoExitHook"/>

</configuration>

=== ymachkivskiy/hage/examples/applications-examples/src/main/resources/examples/configuration/age-collections.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

	<include file="classpath:examples/common.xml">
		<block name="workplaces">
			<component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
				<property name="agent">
					<agent name="action" class="org.jage.agent.SimpleAggregate">
						<property name="agents">
							<list>
								<agent name="list" class="org.jage.examples.configuration.ListAgent">
									<list name="object-example">
										<component class="org.jage.examples.configuration.ExampleClass"
										           isSingleton="false">
											<constructor-arg value="First object"/>
										</component>

										<component class="org.jage.examples.configuration.ExampleClass"
										           isSingleton="false">
											<constructor-arg value="Second object"/>
										</component>

										<component class="org.jage.examples.configuration.ExampleClass"
										           isSingleton="false">
											<constructor-arg value="Third object"/>
										</component>
									</list>
								</agent>

								<agent name="map" class="org.jage.examples.configuration.MapAgent">
									<map name="object-example">
										<entry key="example-1">
											<component class="org.jage.examples.configuration.ExampleClass"
											           isSingleton="false">
												<constructor-arg value="First object"/>
											</component>
										</entry>
										<entry key="example-2">
											<component class="org.jage.examples.configuration.ExampleClass"
											           isSingleton="false">
												<constructor-arg value="Second object"/>
											</component>
										</entry>
										<entry key="example-3">
											<component class="org.jage.examples.configuration.ExampleClass"
											           isSingleton="false">
												<constructor-arg value="Third object"/>
											</component>
										</entry>
									</map>
								</agent>
							</list>
						</property>
					</agent>
				</property>
			</component>
		</block>

		<block name="stopCondition">
			<component name="stopCondition" class="org.jage.workplace.FixedStepCountStopCondition">
				<constructor-arg type="Long" value="1"/>
			</component>
		</block>
	</include>
</configuration>

=== ymachkivskiy/hage/algorithms/applications/binary-genetic/src/main/resources/age.xml
<?xml version="1.0" encoding="UTF-8" ?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://age.iisg.agh.edu.pl/schema/age"
               xsi:schemaLocation="http://age.iisg.agh.edu.pl/schema/age http://age.iisg.agh.edu.pl/schema/age/age.xsd">

    <include file="classpath:common.xml">
        <block name="workplaces">
            <component name="workplace" class="org.jage.workplace.SimpleWorkplace" isSingleton="false">
                <property name="agent">
                    <agent name="action" class="org.jage.agent.SimpleAggregate">
                        <property name="agents">
                            <list>
                                <agent name="agent" class="org.jage.genetic.agent.GeneticActionDrivenAgent">
                                </agent>
                            </list>
                        </property>
                    </agent>
                </property>
            </component>
        </block>
        <block name="workplaceComponents" override="false">
            <!-- Strategies -->
            <strategy name="populationFactory" class="org.jage.population.PopulationFactory">
                <property name="populationSize" type="Integer" value="${population.size}"/>
            </strategy>
            <strategy name="solutionFactory" class="org.jage.solution.binary.BinarySolutionFactory"/>

            <strategy name="populationEvaluator" class="org.jage.evaluation.SequentialPopulationEvaluator"/>
            <strategy class="org.jage.evaluation.binary.M7Evaluator"/>
            <strategy class="org.jage.problem.binary.M7Problem"/>

            <strategy name="rand" class="org.jage.random.SimpleGenerator">
                <constructor-arg type="Long" value="1234567890"/>
            </strategy>

            <strategy name="geneticActionPreparator" class="org.jage.genetic.action.GeneticActionPreparer"/>

            <strategy name="initializationAction" class="org.jage.genetic.action.InitializationActionStrategy"/>
            <strategy name="preselectionAction" class="org.jage.genetic.action.PreselectionActionStrategy"/>
            <strategy name="variationAction" class="org.jage.genetic.action.VariationActionStrategy"/>
            <strategy name="evaluationAction" class="org.jage.genetic.action.EvaluationActionStrategy"/>
            <strategy name="statisticsUpdateAction" class="org.jage.genetic.action.StatisticsUpdateActionStrategy"/>

            <strategy name="preselection" class="org.jage.genetic.preselection.StochasticPreselection">
                <strategy name="scaling" class="org.jage.genetic.scaling.SimpleScaling"/>
            </strategy>

            <strategy name="variation" class="org.jage.variation.VariationOperator">
                <strategy name="recombinePopulation" class="org.jage.variation.recombination.PairedRecombinePopulation">
                    <property name="chanceToRecombine" type="Double" value="${individual.chanceToRecombine}"/>
                    <strategy name="recombineSolution"
                              class="org.jage.variation.recombination.binary.BinaryOnePointRecombine"/>
                </strategy>
                <strategy name="mutatePopulation" class="org.jage.variation.mutation.IndividuallyMutatePopulation">
                    <property name="chanceToMutate" type="Double" value="${individual.chanceToMutate}"/>
                    <strategy name="mutateSolution" class="org.jage.variation.mutation.binary.BinaryMutate">
                        <property name="chanceToMutate" type="Double" value="${feature.chanceToMutate}"/>
                    </strategy>
                </strategy>
            </strategy>
        </block>
    </include>
</configuration>
